spring:
  application:
    name: starter
  datasource:
    url: jdbc:mysql://localhost:3306/starter
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  ldap:
    base: dc=imooc,dc=com
    embedded:
      base-dn: dc=imooc,dc=com
      ldif: classpath:test-ldap-server.ldif
      port: 8389
    urls: ldap://localhost:8389/
server:
  port: ${SERVER_PORT:8090}
logging:
  level:
    level: info
  file:
    name: starter.log
