spring:
  datasource:
    url: jdbc:mysql://localhost:3306/starter
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  application:
    name: starter
server:
  port: ${SERVER_PORT:8090}
logging:
  level:
    level: info
  file:
    name: starter.log
